
```{r}
#reading in data spreadsheets
firearmsData <- read.csv("firearmsData.csv")
clinton <- read.csv("CLINTON1998-2001.csv")
bush <- read.csv("BUSH2001-2009.csv")
obama <- read.csv("OBAMA2009-2017.csv")
trump <- read.csv("TRUMP2017-2020.csv")
biden <- read.csv("BIDEN2020-2021.csv")
```

```{r}
#adding the "totals" column for each presidential term
sum(clinton$totals)
sum(bush$totals)
sum(obama$totals)
sum(trump$totals)
sum(biden$totals)
```

```{r}
#estimating what the differences would be if the data set was complete
#Clinton was in office 1996-2001, data is 1998-2001 (missing two years, so multiplying to estimate 4 year term)
clintonSum <- sum(clinton$totals)*2 
clintonSum
bushSum <- sum(bush$totals)
bushSum
#dividing Obama's term by 2 so it estimates a 4 year term
obamaSum <- sum(obama$totals)/2 
obamaSum
trumpSum <- sum(trump$totals)
trumpSum
#only been in office about two years, so multiplying by two to estimate four year term
bidenSum <- sum(biden$totals)*2
bidenSum
```

```{r}
#finding max value of firearms sales during each year 
max(clinton$totals)
max(bush$totals)
max(obama$totals)
max(trump$totals)
max(biden$totals)
```


```{r}
#finding entry for max firearm sales during Clinton Administration
#install data.table if haven't already done so
#install.packages("data.table")
library(data.table)
clinton2 <- data.table(clinton)
clinton2
setkey(clinton2, "totals")
head(clinton2)
clinton2[.(max(clinton$totals))]
#1999 CALIFORNIA 136278
```

```{r}
#finding entry for max firearm sales during Bush Administration
library(data.table)
bush2 <- data.table(bush)
bush2
setkey(bush2, "totals")
head(bush2)
bush2[.(max(bush$totals))]
#2008 KENTUCKY 184555
```

```{r}
#finding entry for max firearm sales during Obama Administration
library(data.table)
obama2 <- data.table(obama)
obama2
setkey(obama2, "totals")
head(obama2)
obama2[.(max(obama$totals))]
#2014 NORTH CAROLINA 541978
```

```{r}
#finding entry for max firearm sales during Trump Administration
library(data.table)
trump2 <- data.table(trump)
trump2
setkey(trump2, "totals")
head(trump2)
trump2[.(max(trump$totals))]
#2020 ILLINOIS 612411
```

```{r}
#finding entry for max firearm sales during Biden Administration
library(data.table)
biden2 <- data.table(biden)
biden2
setkey(biden2, "totals")
head(biden2)
biden2[.(max(biden$totals))]
#2021 ILLINOIS 1427917
```

```{r}
#finding the differences between each of the administrations with averaged data
diff1 <- sum(bush$totals)-sum(clinton$totals)*2
print("----DIFFERENCE BW BUSH & CLINTON----")
diff1
diff2 <- sum(trump$totals)-sum(obama$totals)/2
print("----DIFFERENCE BW TRUMP & OBAMA----")
diff2
diff3 <- sum(biden$totals)*2 - sum(trump$totals)
print("----DIFFERENCE BW BIDEN & TRUMP----")
diff3
```

```{r}
#install the following packages if not already done so
#install.packages("tidyverse")
#library(tidyverse)
#plotting summations of all firearm sales during the last five US administrations
points <- c(clintonSum,bushSum,obamaSum,trumpSum,bidenSum)
plot(points, 
     xaxt = "n",
     type = "o", 
     col = "blue", 
     xlab = "A - Clinton   B - Bush   C - Obama   D - Trump   E - Biden",
     ylab = "Firearm Sales", 
     main = "Firearm Sales from 1999-2021")
axis(side = 1,
     at = 1:5,
     labels = LETTERS[1:5])

```